# Generated by Django 5.0.6 on 2024-07-14 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coreteammember',
            name='image',
            field=models.ImageField(upload_to='team_images/'),
        ),
        migrations.AlterField(
            model_name='coreteammember',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='coreteammember',
            name='position',
            field=models.CharField(max_length=100),
        ),
    ]
